version: '3'

services:
  web:
    build: .
    ports: 
      - "41960:8080"
    environment:
      - BASE_URL=http://localhost:8081

  builder:
    image: builder
    ports:
      - "8081:8080"
    environment:
      - OBSIDIAN_VAULT_REPO_LOCATION=/app/vault
    volumes:
      - C:\Users\Alan\Documents\Obsidian Vault\Organizer:/app/vault
